In [19]:
import numpy as np

## 4: create a null vector of size 10 and update sixth value to 11

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
arr = np.zeros(10)
arr.size

10

In [6]:
# update sixth value to 11

arr[6] = 11
arr

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

## 8: create a 2d array with 1 on the border and 0 inside

In [7]:
arr2d = np.ones((5,5))
arr2d

# create original array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
arr2d[1:4, 1:4] = 0
arr2d

# 1 on the border and 0 inside in the array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## 9: Write a NumPy program to add a border (filled with 0's) around an existing array

In [9]:
arr2dn = np.full((3,3), 1, dtype=float)
arr2dn

# creating original array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
addc = np.zeros(3)
addc

# arr2dn array'inin başına ve ve sonuna ilave edeceğimiz column'u create ettik.
# ama bu vektör olduğu için 2 boyutlu array'e bu şekilde ilave edemeyiz.

array([0., 0., 0.])

In [11]:
addc.reshape((3,1))
addc

# vektör olan addc'in shape'ini 2 boyutlu yaptık. şimdi arr2dn'e ekleyebiliriz. 

array([0., 0., 0.])

In [14]:
arr2dn = np.c_[addc, arr2dn, addc]
arr2dn

 # arr2dn'nin başına ve sonuna addc column'unu ilave ettik.

array([[0., 0., 0., 1., 1., 1., 0.],
       [0., 0., 0., 1., 1., 1., 0.],
       [0., 0., 0., 1., 1., 1., 0.]])

In [72]:
addr = np.zeros((1,5)) 
addr

# arr2dn array'inin üstüne ve altına ilave edeceğimiz satırı, 
# arr2dn 2 boyutlu olduğu için 2 boyutlu olarak create ettik.

array([[0., 0., 0., 0., 0.]])

In [73]:
arr2dn = np.r_[addr, arr2dn, addr]  # arr2dn nin üstün ve altına addr row'unu ilave ettik.

In [74]:
arr2dn

# 0 on the border and 1 inside in the array

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [253]:
# np.pad() numpy fonksiyonu ile çözüm: 

arr2dn = np.pad(arr2dn, pad_width=1, mode='constant', constant_values=0)
arr2dn

# bir yukarda arr2dn ye 0 lar eklendiği için bir sıra daha eklenmiş oldu.

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

## bir array'a column ve row eklemek (cevaba ilave bilgi)

In [82]:
import numpy as np
N = 3 
A = np.eye(N)

np.c_[ A, np.ones(N) ]              # add a column



array([[1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 0., 1., 1.]])

In [83]:
np.c_[ np.ones(N), A, np.ones(N) ]  # or two

array([[1., 1., 0., 0., 1.],
       [1., 0., 1., 0., 1.],
       [1., 0., 0., 1., 1.]])

In [84]:
np.r_[ A, [A[1]] ]              # add a row


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [85]:
np.r_[ A[0], 1, 2, 3, A[1] ]    # mix vecs and scalars


array([1., 0., 0., 1., 2., 3., 0., 1., 0.])

In [86]:
np.r_[ A[0], [1, 2, 3], A[1] ]  # lists


array([1., 0., 0., 1., 2., 3., 0., 1., 0.])

In [87]:
np.r_[ A[0], (1, 2, 3), A[1] ]  # tuples


array([1., 0., 0., 1., 2., 3., 0., 1., 0.])

In [88]:
np.r_[ A[0], 1:4, A[1] ]        # same, 1:4 == arange(1,4) == 1,2,3


array([1., 0., 0., 1., 2., 3., 0., 1., 0.])

##  append ile array'a column eklemek (cevaba ilave bilgi)

In [89]:
a = np.array([[1,2,3],[2,3,4]])
a

# orjinal array'imizi create ettik.

array([[1, 2, 3],
       [2, 3, 4]])

In [93]:
z = np.zeros((2,1), dtype = int)
z

# ekleyeceğimz sütunu create ettik.

array([[0],
       [0]])

In [94]:
np.append(a, z, axis=1)

# a array'ine z sütununu append ile ekledik.
# axis parametresine sütunu temsil eden değer olan 1'i assign ettiğimize dikkat et 

array([[1, 2, 3, 0],
       [2, 3, 4, 0]])

## 10: Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [114]:
arr2d8 = np.zeros((8,8), dtype = int)
arr2d8

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [140]:
# Checkerboard pattern:

for i in range(8):
    if not i % 2 :
        for j in range(8):
            if j % 2:
                arr2d8[i][j] = 1
            else:
                arr2d8[i][j] = 0
    else :
        for j in range(8):
            if not j % 2:
                arr2d8[i][j] = 1
            else:
                arr2d8[i][j] = 0
print(arr2d8)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
# slicing ile çözümü:

x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x

Checkerboard pattern:


array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [25]:
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 12: Write a NumPy program to append values to the end of an array

In [30]:
arr3 = np.array([10, 20, 30])
arr3

array([10, 20, 30])

In [31]:
arr4 = np.array([40, 50, 60, 70, 80, 90])

In [32]:
# arr3 = np.append(arr3, [40, 50, 60, 70, 80, 90], axis=0)
arr3 = np.append(arr3, arr4, axis=0)
arr3

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [186]:
x = [10, 20, 30]
print("Original array:")
print(x)
x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print("After append values to the end of the array:")
print(x)

Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


## 14: Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.

In [160]:
Fah = [ 0., 12., 45.21, 34., 99.91]

In [184]:
fah = np.array(Fah)
print("Fahrenheit degrees :", fah)

Fahrenheit degrees : [ 0.   12.   45.21 34.   99.91]


In [185]:
cel = (fah - 32) / 1.8

print("Centigrade degrees :", cel)

Centigrade degrees : [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


## 19: Write a NumPy program to get the unique elements of an array.

In [165]:
arr5 = np.array([10, 10, 20, 20, 30, 30])

arr5

array([10, 10, 20, 20, 30, 30])

In [167]:
unique = []
for i in arr5 :
    if i not in unique:
        unique.append(i)
print("Unique elements of the above array:", unique)

Unique elements of the above array: [10, 20, 30]


In [181]:
# np.unique fonksiyonu ile çözümü

print("Unique elements of the array:", np.unique(arr5))

Unique elements of the above array: [10 20 30]


In [182]:
arr6 = np.array([[1, 2, 2], [4, 5, 4], [2, 1, 3]])

arr6

array([[1, 2, 2],
       [4, 5, 4],
       [2, 1, 3]])

In [183]:
print("Unique elements of the array:", np.unique(arr6))

Unique elements of the array: [1 2 3 4 5]


In [33]:
import pandas as pd

## 2: Write a Pandas program to convert a Pandas module Series to Python list and it's type.

In [2]:
list = [1, 5, 10, 15, 20]

In [5]:
ser = pd.Series(data = list)

ser

0     1
1     5
2    10
3    15
4    20
dtype: int64

In [6]:
type(ser)

pandas.core.series.Series

In [7]:
ser.tolist()

[1, 5, 10, 15, 20]

In [8]:
print(type(ser.tolist()))

<class 'list'>


In [9]:
ser

0     1
1     5
2    10
3    15
4    20
dtype: int64

In [15]:
ser.to_list()

[1, 5, 10, 15, 20]

In [12]:
ser.to_dict()

{0: 1, 1: 5, 2: 10, 3: 15, 4: 20}

In [16]:
ser.to_string()

'0     1\n1     5\n2    10\n3    15\n4    20'

## 3: Write a Pandas program to add, subtract, multiple and divide two Pandas Series.

In [18]:
list1 = [2, 4, 6, 8, 10]
list2 = [1, 3, 5, 7, 9]

In [19]:
ser1 = pd.Series(list1)
ser2 = pd.Series(list2)

In [20]:
ser_add = ser1 + ser2

ser_add

# ser1 ile ser2 nin elemanlarını karşılıklı toplayıp yeni bir seri elde ettik.

0     3
1     7
2    11
3    15
4    19
dtype: int64

In [21]:
ser_subt = ser1 - ser2

ser_subt

0    1
1    1
2    1
3    1
4    1
dtype: int64

In [22]:
ser_mult = ser1 * ser2

ser_mult

0     2
1    12
2    30
3    56
4    90
dtype: int64

In [24]:
ser_mult = np.multiply(ser1,ser2)
ser_mult

0     2
1    12
2    30
3    56
4    90
dtype: int64

In [212]:
ser_div = ser1 / ser2

ser_div

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [202]:
 # bu da iki seriyi birleştirip onlardan dataFrame yapmak

df = pd.concat([ser1, ser2], axis = 1)
df

0  1
0   2  1
1   4  3
2   6  5
3   8  7
4  10  9

  ## 5: Write a Pandas program to convert a dictionary to a Pandas series.

In [26]:
keys=['a','b','c','d','e']
values = [100, 200, 300, 400, 800]

In [228]:
print(*zip(keys, values))

('a', 100) ('b', 200) ('c', 300) ('d', 400) ('e', 800)


In [27]:
d = {}
for i, ii in zip(keys, values):
    d[i] = ii
d

{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

In [232]:
# Create a dictionary from keys and values

dict1 = {}
for a, b in zip(keys, values) :
    dict1[a] = b
dict1

{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

In [233]:
# dict1'i seriye çevirme:

series = pd.Series(dict1)

series

a    100
b    200
c    300
d    400
e    800
dtype: int64

## 6: Write a Pandas program to convert a NumPy array to a Pandas series.

In [234]:
data = [10, 20, 30, 40, 50]

In [235]:
# Create a numpy array with this data

arr = np.array(data)

arr

array([10, 20, 30, 40, 50])

In [236]:
# Convert a NumPy array to Pandas series.

ser = pd.Series(arr)

ser

0    10
1    20
2    30
3    40
4    50
dtype: int32

## 12: Write a Pandas program to add some data to an existing Series.|

In [237]:
data1 = ['100', '200', 'python', '300.12', '400']

In [240]:
# Built a pandas Series with this data

ser1 = pd.Series(data1)
print("Original Data Series :\n", ser1)


Original Data Series :
 0       100
1       200
2    python
3    300.12
4       400
dtype: object


In [31]:
# Add ['500', 'php'] to the original Data Series

ser2 = pd.Series(['500', 'php'])
ser2

ser1.append(ser2)

0      2
1      4
2      6
3      8
4     10
0    500
1    php
dtype: object

In [247]:
# Add ['500', 'php'] to the original Data Series ignoring index

ser2 = pd.Series(['500', 'php'])
ser2

ser1.append(ser2, ignore_index = True)

0       100
1       200
2    python
3    300.12
4       400
5       500
6       php
dtype: object

### başka bir örnek

In [241]:
s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])
s3 = pd.Series([4, 5, 6], index=[3, 4, 5])
s1.append(s2)

0    1
1    2
2    3
0    4
1    5
2    6
dtype: int64

In [242]:
s1.append(s3)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [243]:
s1.append(s2, ignore_index=True)

# s2nin indeks numaralarının ignore edildiğini ve default olarak verildiğini gör.

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

## 13: Write a Pandas program to create a subset of a given series based on value and condition.

In [34]:
data3 = [0,1,2,3,4,5,6,7,8,9,10]

In [35]:
# Built a pandas Series with this data

ser3 = pd.Series(data3)

ser3

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

In [250]:
# Create a new series with data with a value less than 6

ser_new = pd.Series(ser3 < 6)

ser_new

0      True
1      True
2      True
3      True
4      True
5      True
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [252]:
ser_new = ser3[ser3 < 6]

ser_new

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

In [38]:
ser3[pd.Series(ser3<6)]

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

In [40]:
arr = np.array([11, 12, 13, 14, 15, 16, 17, 15, 11, 12, 14, 15, 16, 17])

In [112]:
result = np.where(arr == 15)
result

(array([ 4,  7, 11], dtype=int64),)

In [41]:
np.where(arr > 15)

(array([ 5,  6, 12, 13], dtype=int64),)

In [42]:
arr[np.where(arr > 15)]

array([16, 17, 16, 17])