In [1]:
import numpy as np 

# herşeyden önce numpy i import ediyoruz. Numpy = Numerical Python

# array oluşturma : liste kullanarak_array fonksiyonu ile_arange fonsiyonu ile_linspace fonksiyonu ile

mylist = [1, 2, 3]

In [3]:
type(mylist)

list

In [4]:
np.array([1, 2, 3])

# array metodu ile listeyi dizine çevirdik. artık o bir array

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [6]:
myarr = np.array(mylist)

# mylist değişkenini kullanarak aynı şekilde dizin oluşturup myarr değişkenine bunu atadık. 

In [7]:
type(myarr)

# myarr değişkeninin tipinin array olduğunu görelim

numpy.ndarray

In [11]:
liste = [1,2,3,4,5,6,7,8]
a = np.array(liste)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
type(a)

numpy.ndarray

In [13]:
a.shape

# a dizisin boyutunu veriyor. (tuple içinde belirtiyor)
# burada 8'e 0 boyutlu olduğunu yani bir VEKTÖR olduğunu görüyoruz

(8,)

In [16]:
# şimdi 2 boyutlu bir matris yapalım.

b = np.array([[1,2,3], [6,7,8]])
b

array([[1, 2, 3],
       [6, 7, 8]])

In [17]:
b.shape

# b matrisinin 2 satır 3 sütundan oluştuğunu gördük.

(2, 3)

In [18]:
b[1,1]

7

In [19]:
c = np.array([[1,2,3], [4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
c.shape

(3, 3)

In [21]:
# c matrisinde 5 i çağıralım

c[1,1]  # 1.satırın 1. sütununu çektik

5

In [6]:
my_matrix = [[1,2,3], [4,5,6],[7,8,9]]

# 3 listeden oluşan bir liste yapalım ve daha sonra bunu array matrix haline getirelim.

In [7]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

# 3 sütun ve 3 satırdan oluşan bir matrix oluşturuldu. bu 3 boyutlu bir arraydır

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10)

# arange metodu belirli bir aralıkta eşit aralıklı değerler döndürür.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,10,2) 

# 0 dan 10 a kadar (10 hariç) 2 şer atlayarak dizi oluşturduk

array([0, 2, 4, 6, 8])

In [15]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [16]:
np.zeros(5)

# eğer tek bir rakam girersen bu girilen rakam kadar sıfırların bir boyutlu bir vektörünü oluşturur 
# default olarak bu sıfırlar float olacaktır.

array([0., 0., 0., 0., 0.])

In [18]:
# şimdi 2 boyutlu dizi oluşturalım

np.zeros((2,5))

# 2 satır 5 sütundan oluşan  2 boyutlu dizi oluşturduk

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.zeros((4,4))

# sıfırlardan 4 satır 4 sütundan oluşan 2 boyutlu dizi oluşturduk

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.zeros((4,4), dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [20]:
np.ones(5)

# bir ile başlayan sayılardan oluşan dizi oluşturduk.

array([1., 1., 1., 1., 1.])

In [5]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:

np.ones((3, 5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
np.ones((4,4), dtype=str)

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [4]:
np.ones((4,4), dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [8]:
np.full((3, 5), "3", order = "F") 

# "C" C language "F" fortran language
# Whether to store multidimensional data in C- or Fortran-contiguous 
# (row- or column-wise) order in memory.

array([['3', '3', '3', '3', '3'],
       ['3', '3', '3', '3', '3'],
       ['3', '3', '3', '3', '3']], dtype='<U1')

In [9]:
np.full((3, 5), "3")

array([['3', '3', '3', '3', '3'],
       ['3', '3', '3', '3', '3'],
       ['3', '3', '3', '3', '3']], dtype='<U1')

In [22]:
np.full((3, 3), "michael")

array([['michael', 'michael', 'michael'],
       ['michael', 'michael', 'michael'],
       ['michael', 'michael', 'michael']], dtype='<U7')

In [24]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.arange(5, 60, 3)

# 3'er 3 er atlayarak belirtilen aralıkta sayılar üret

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
       56, 59])

In [21]:
np.linspace(0,10,3)

# bize girilen aralık boyunca doğrusal(lineerly spaced) veya eşit aralıklı (evenly spaced) üç sayı verir
# aralığın ilk ve son rakamları DAHİL.. üçüncü parametre, arada olmasını istediğimiz rakam adedidir.
# (start, stop, arada olmasını istediğin rakam sayısı)

array([ 0.,  5., 10.])

In [22]:
np.linspace(0,10,11)

# 0 ile başlayıp aralığın son rakamını da içereceğinden son parametreyi 11 yaptık.
# böylece sıfırdan 10 a kadar sırayla artan dizi elde ettik.

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
# 0,10 arasında 10 rakam var zannedip yanlışlıkla son parametreyi 10 girersen şu sonuç çıkar

np.linspace(0,10,10)

# eleman sayısından 1 az girersek girilen rakam sayısı kadar eleman üreteğinden ve bunları 
# eşit dağıtmaya çalışacağından aşağıdaki gibi olacaktır.. 
# o yüzden düzgün bir dağılım istiyorsan hep son rakamın bir fazlasını girmelisin

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [25]:
np.linspace(0,5,21)

# arada 21 rakam olmasını istedik.

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [26]:
len(np.linspace(0,5,21))

# arada 21 rakam var olduğunu görelim

21

# şimdi random dağıtılan bir data oluşturalım.

# random.random

In [28]:
np.random.random((3,3))

array([[0.84894259, 0.74670928, 0.20855969],
       [0.23121625, 0.88447983, 0.24876371],
       [0.02039738, 0.00632578, 0.46253131]])

# random.rand

In [ ]:
np.random.rand(1)

# 0 ile 1 arasında random olarak belirlenen adette sayı üretir.

# create an array of the given shape and populate it with random
# samples from a uniform distribution
# over the points zero to one where zero is inclusive and one is exclusive
# meaning it can't actually return back zero, but it can't return back one

In [29]:
np.random.rand(1)

array([0.38686083])

In [30]:
np.random.rand(1)

#  0 ile 1 arasında rastgele 1 sayı ürettik.

array([0.44651195])

In [31]:
np.random.rand(5,6) 

# 0 ile 1 arasında random 5 satırlı 6 sütunlu dizi üretelim

array([[0.69935643, 0.36860551, 0.52821359, 0.81711766, 0.81866543,
        0.07180148],
       [0.87924289, 0.83037341, 0.84417922, 0.29996816, 0.82869024,
        0.94450068],
       [0.56979391, 0.28355955, 0.77029627, 0.40245608, 0.84154511,
        0.30939489],
       [0.10077143, 0.0361382 , 0.43768353, 0.56680731, 0.8399808 ,
        0.47600595],
       [0.32094805, 0.83890494, 0.25722065, 0.12061454, 0.1015587 ,
        0.76905387]])

# random.randn

In [ ]:
"""
np.random.randn()

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.
"""
# belirtilen sayı kadar, orta noktası sıfır olan kayan noktalı sayı üretir

In [34]:
np.random.randn(10)

array([ 0.24784654,  0.92963903, -1.50431776,  0.33741729, -1.08532412,
        0.97755546,  0.65539302, -0.26867746,  1.08810725, -0.4135954 ])

In [35]:
np.random.randn(2, 3)

# aynı şekilde bu sefer 2 satırlı 3 sütunlu dizi ürettik

array([[ 0.30339632, -1.62017238, -1.94259546],
       [ 0.67227086, -0.89518969,  0.36798695]])

# random.randint

In [ ]:
"""
np.random.randint()

Return random integers from `low` (inclusive) to `high` (exclusive)
""""
# Bu 0 ile 1 arasında değil, istediğin sayılar arasında random sayı üretir.
# girilen en düşük (dahil) ve en yüksek (hariç) sayılar arasında belirtilen miktarda random sayı üretir.

In [36]:
np.random.randint(0, 101, 5)

# 0 ile 101 arasında 5 adet random sayı ürettik

array([97,  9, 79, 55, 50])

In [37]:
np.random.randint(0, 101, 10)

array([19, 88, 21, 67, 34, 78, 27, 40, 97, 92])

In [3]:
z = np.random.randint(2, 15, size = (5, 3))
z

# 2 ile 15 arasında random olarak rakamlar üretecek ve bu 5 e 3 matris olacak

array([[ 8,  9,  6],
       [12,  6,  7],
       [12,  5, 14],
       [ 7,  6,  5],
       [11,  9, 13]])

In [31]:
z.shape

(5, 3)

In [34]:
z = z.reshape(3, 5)
z

# 5'e 3 olan matrisi 3'e 5 yaptık

array([[12,  8,  7,  9,  8],
       [ 9,  6,  2,  3, 14],
       [ 2, 13,  8,  6,  8]])

In [35]:
z.shape

(3, 5)

In [36]:
z.ravel()

# Return a flattened array

array([12,  8,  7,  9,  8,  9,  6,  2,  3, 14,  2, 13,  8,  6,  8])

In [4]:
z.max()

14

In [5]:
z.min()

5

In [6]:
z.argmax()

8

In [7]:
z.argmin()

7

# random.seed

In [ ]:
"""
np.random.seed()

seed set edebilmek çok kullanışlıdır. seed, rastgele durum üretir. 
böylece rastgele sonuıçlar yeniden üretilebilir.
"""

In [38]:
np.random.seed(42)
np.random.rand(4)

# so what the seed allows us to do is set a particular set of random numbers.
# seed burda bize belirli bir rasgele sayılar kümesi ayarladı.
# 42 burada tamamen keyfi bir seçim


array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [39]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [40]:
np.random.rand(4)

array([0.68527698, 0.83389686, 0.30696622, 0.89361308])

In [41]:
np.random.rand(4)

# 101 ile set ettikten sonra her np.random.rand(4) fonksiyonu bize ayrı bir random dizi verecektir.

array([0.72154386, 0.18993895, 0.55422759, 0.35213195])

In [42]:
np.random.seed(101)
np.random.rand(4)

# fakat 101'i tekrar set ettiğimizde yeniden bize ilk orjinal diziyi verecektir.

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

# arange, reshape

In [9]:
import numpy as np

arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [3]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
arr.reshape(5,5)

# 5 e 5 matrix oluşturduk. dizide 25 eleman olduğu için bu oldu. 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
arr.reshape(5,4)

# 25 eleman olduğu için 5 e 4 matrix hata verecektir.

ValueError: cannot reshape array of size 25 into shape (5,4)

# max, min, argmax, argmin, dtype

In [10]:
ranarr = np.random.randint(0,101,10)

In [8]:
ranarr

array([79, 68, 37, 11, 48, 39, 85, 27, 34, 34])

In [9]:
ranarr.max()

85

In [10]:
ranarr.min()

11

In [11]:
ranarr.argmax()

# maksimun rekamın indeksini verir

6

In [12]:
ranarr.argmin()

# minimum rekamın indeksini verir

3

In [13]:
ranarr.dtype

 # array'ın tipinin integer olduğunu görelim.

dtype('int32')

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [12]:
arr.shape

# dizi şekilini görüntüleyelim ve 1 boyutlu olduğunu görelim.

(25,)

In [13]:
arr.reshape(5,5)

# diziyi reshape ile 5 e 5 matrix olarak şekillendirdik.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
arr.shape

# dizinin şekilini görüntüleyelim

(25,)

In [18]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [19]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [51]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


# Numpy Operations

In [1]:
import numpy as np

In [17]:
arr = np.arange(0,10)

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr + 5

# dizideki bütün elemanlarına 5 ekledik

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr * arr

# dizideki tüm elemanlarını kendisi ile çarparak karelerini almış olduk

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [23]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr / arr

# ilk elemanı 0 olduğu için o indekste hata oluştu.ama yine de dizini bozmadı.

c:\users\hüseyin\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [27]:
1 / 0

# buradaki hata mersajına dikkat.. 

ZeroDivisionError: division by zero

In [28]:
1 / arr

# burdaki hata mesajına dikkat..

c:\users\hüseyin\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [33]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

In [34]:
x + y

array([[ 6,  8],
       [10, 12]])

In [35]:
x - y

array([[-4, -4],
       [-4, -4]])

In [36]:
np.subtract(x, y)

array([[-4, -4],
       [-4, -4]])

In [37]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [38]:
x * y

array([[ 5, 12],
       [21, 32]])

In [40]:
x

array([[1, 2],
       [3, 4]])

In [41]:
y

array([[5, 6],
       [7, 8]])

In [39]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [42]:
x @ y

# np.dot ile aynı işi yapıyor

array([[19, 22],
       [43, 50]])

In [43]:
x / y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [44]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [45]:
x

array([[1, 2],
       [3, 4]])

In [46]:
x ** 2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [47]:
x1 = np.square(x)

In [48]:
x1

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [49]:
np.sqrt(x1)

array([[1., 2.],
       [3., 4.]])

In [29]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [30]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [31]:
np.log(arr)

c:\users\hüseyin\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [32]:
arr.sum()

45

In [33]:
arr.mean()

4.5

In [34]:
arr.max()

9

In [36]:
arr.var()

# variation

8.25

In [35]:
arr.std()

 # standart deviation.

2.8722813232690143

In [37]:
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arr2d = np.arange(0,25).reshape(5,5)

# aynı anda arange metodu ile 0 ile 25 arası rakam üretip bunu rshape metodu ile 5 e 5 şekillendip arr2d değişkenine atadık

In [40]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
arr2d.sum()

# bütün satır ve sütunları topladık.

300

In [42]:
arr2d.sum(axis=0)

# axis i sıfıra eşitlemekle sadece sütunları işleme kattık. (0,5,10,15,20 = 50)
# her bir sütunu toplayıp bir eleman yaptı.
# !! default olarak axis=None dır.

array([50, 55, 60, 65, 70])

In [43]:
arr2d.sum(axis=1)

# axis i sıfıra eşitlemekle sadece satırları işleme kattık. (0,5,10,15,20 = 10)

array([ 10,  35,  60,  85, 110])

In [3]:
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1) - np.max(arr_2)

# ilk dizideki sayıların kareköklerini alıp her birini ikinci dizideki max elemanında çıkartıyoruz.

array([-4., -3., -2., -1.,  0.])

In [61]:
arr_1 = np.array([5,6,7])
arr_2 = np.array([4,5,6])
arr_1 - arr_2

# birinci diziden ikinci diziyi çıkartıyoruz.

array([1, 1, 1])

In [62]:
arr_1 * arr_2

array([20, 30, 42])

In [63]:
np.dot(arr_1, arr_2)

"""
Dot product of two arrays. Specifically,

- If both `a` and `b` are 1-D arrays, it is inner product of vectors
  (without complex conjugation).

- If both `a` and `b` are 2-D arrays, it is matrix multiplication,
  but using :func:`matmul` or ``a @ b`` is preferred.
"""

92

In [64]:
arr_1@arr_2 

# np.dot ile aynı işi yapıyor

92

In [66]:
x = np.square(arr_1)
x

# arr_1 in karesini alıp yeni oluşan matrisi x değikenine atadık

array([25, 36, 49], dtype=int32)

In [67]:
np.sqrt(x)
# x'in tekrar karekökünü aldık

array([5., 6., 7.])

In [68]:
np.exp(3)

20.085536923187668

In [69]:
np.log10(100)

2.0

In [76]:
t = np.array([np.pi/6, np.pi/2, np.pi/3])
t

array([0.52359878, 1.57079633, 1.04719755])

In [77]:
np.sin(t)

array([0.5      , 1.       , 0.8660254])

# Numpy Indexing and Selection

In [56]:
import numpy as np

In [ ]:
arr = np.arange(0,11)

In [46]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr[8]

# 8.indexteki rakam

8

In [48]:
arr[1:5]

# aynı list indexing gibi

array([1, 2, 3, 4])

In [49]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [50]:
arr[:5]

array([0, 1, 2, 3, 4])

In [51]:
arr[5:]

array([5, 6, 7, 8, 9])

In [52]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr[0:5] = 100

# 0 ile 5. index arasındaki elemanlara 100 değeri atadık.
# yani reassignment yapabiliyoruz. bunu normal python listelerinde yapamıyorduk!!!

In [54]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [58]:
arr = np.arange(0,11)

In [60]:
slice_of_arr = arr[0:5]

# dizinin ilk 5 elamanını slice_of_arr değişkenine atadık.
# birazdan bu değikene yaptığımız değişikliklerin orjinal arr dizisinde de değişikliğe neden olacağını göreceğiz!

In [61]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [62]:
slice_of_arr[:] = 99

In [63]:
slice_of_arr

# yukarda slice_of_arr değişkenine dizinin 0:5 indekslerini atamıştık. 
# sonra da bu değişkenin elemanlarına 99 rakamını eşitledik.
# sonuç olarak orjinal arr isimli dizinin 0:5 indeksindeki elemanları da değişmiş oldu. 
# arr'a bakarak değiştiğini görelim

array([99, 99, 99, 99, 99])

In [64]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [66]:
arr_copy = arr.copy()

# arr ın kopyasını arr_copy değişkenin atayarak kopyasını alalım.
# ve bu kopya üzerinde yapacağımız değişikliklerin orjinal arr dizisi üzerindeki sonuçlarına bakalım

In [67]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [68]:
arr_copy[:] = 100

# arr_copy değişkeninin tüm elemanlarını 100 e eşitledik. bakalım orjinal arr dizisinde değişiklik olacak mı

In [69]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [70]:
arr

# orjinal dizide değişiklik olmadı. çünkü diziyi copy metodu ile bir değişkene kopyalayarak atadığımızda 
# müteakip değişiklikler yalnızca kopya değişken üzerinde olacaktır

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [71]:
# şimdi 2 boyutlu dizi üzerinde indexing yapalım. önce bir dizi oluşturalım 

arr_2d = np.array([[5,10,15], [20,25,30], [35,40,50]])

In [72]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [73]:
arr_2d.shape

# bu dizinin şekline bakalım. 3 satır 3 sütun olduğun görelim

(3, 3)

In [74]:
arr_2d[0]

# sıfırıncı indeksi sıfırıncı satırı yani ilk satırı verecektir.

array([ 5, 10, 15])

In [75]:
arr_2d[2]

# 2. index de 3 satırı verecektir.

array([35, 40, 50])

In [76]:
# şimdi index yoluyla 2. satırın 2. elemanına ulaşalım

arr_2d[1,1]

# arasını virgülle ayırarak 1,1 yazdığımızda 1. indexteki yani 2. satırın, 1. index elemanını yani 25'i bulduk

25

In [77]:
arr_2d[0,2]

15

In [ ]:
# şimdi de birinci ve ikinci satırların 2. ve 3. elemanlarını çekelim. yani 10,15 ve 25,30

In [78]:
arr_2d[:2]

# :2, 0 ve 1. satırları getirdi.

array([[ 5, 10, 15],
       [20, 25, 30]])

In [79]:
arr_2d[:2,1:]

# araya koyacağımız virgülden sonrası sütunları seçmemizi sağlayacak.
# böylece 0 ve 1. satıların, 1.indeksinden sonraki sütunlarını almış olduk

array([[10, 15],
       [25, 30]])

 # çok daha fazla yaygın olan selection tipi conditional selection'dır. şimdi bunu görelim.

In [80]:
arr = np.arange(1,11)

In [81]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
# benim 4'ten büyük dizi elemanlarım nerede bulalım.

arr > 4

# sonucun boolean çıktığına dikkat et.  4 ten büyük olanlar True çıktı.

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [85]:
bool_arr = arr > 4

# aslında bu arr büyük müdür 4'ten sorusunu sorar. bu sorunun cevabını bool_arr değişkenine atadık.

In [86]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [87]:
arr[bool_arr]

# arr dizisinin bool_arr sonucu True olan elemanlarını conditioanl index yaparak filtreleyip çektik.

array([ 5,  6,  7,  8,  9, 10])

In [88]:
arr[arr > 4]

# aradan bool_arr değişkenini çıkartarak conditional indexleme yaptık.

array([ 5,  6,  7,  8,  9, 10])

# Stacking

In [19]:
# istenen eksen üzerinde iki array i birleştirme yapıyor

a = np.array([[1,2], [3,4]])
b = np.array([[-1,3], [7,9]])

In [20]:
a

array([[1, 2],
       [3, 4]])

In [15]:
b

array([[-1,  3],
       [ 7,  9]])

In [16]:
np.hstack((a,b))

# hstack = horizantal olarak birleştiriyor. iki arrayın satır sayıları aynı olmalı.

array([[ 1,  2, -1,  3],
       [ 3,  4,  7,  9]])

In [43]:
np.vstack((a,b))

# hstack = vertical olarak birleştiriyor. iki arrayın sütun sayıları aynı olmalı.

array([[ 1,  2],
       [ 3,  4],
       [-1,  3],
       [ 7,  9]])

In [45]:
a = np.array([[1,2], [3,4], [5,6]])
b = np.array([[-1,3], [7,9]])

np.hstack((a,b))

# sütun sayıları aynı olmadığından hata verecek

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

#  Concatenate

In [23]:
dizi = np.array([0,1,2,3,4,5,6,7,8,9]).reshape((5,2))

In [24]:
dizi

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [25]:
dizi_1 = np.array([3,4,5,6,7,8,9,10,11,12]).reshape(5,2)

In [26]:
dizi_1

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [27]:
np.concatenate([dizi, dizi_1], axis = 0)

# axis=0 diyerek satır olarak seçmiş olduk. ve her iki matrisin satırlarını alt alta birleştirik.

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [28]:
np.concatenate([dizi, dizi_1], axis = 1)

# her iki matrisin sütünlarını yan yana birleştirdik.
# birinci satırların sütunlarını aynı satırda birleştirdik.4
# ve diğer satırlara da aynı işlemi yaptık

array([[ 0,  1,  3,  4],
       [ 2,  3,  5,  6],
       [ 4,  5,  7,  8],
       [ 6,  7,  9, 10],
       [ 8,  9, 11, 12]])

In [48]:
array_1 = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])

In [49]:
array_1.shape

(3, 4)

In [50]:
array_1[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [51]:
array_2  = array_1.copy()

In [52]:
array_2

# orjinal array in değişmesini istemiyorsan 
# kopyasını başka bir değişkene ata ve onun üzerinde değişiklik yap.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
array_2[1,1] = -6

array_2

array([[ 1,  2,  3,  4],
       [ 5, -6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
array_1

# array_1'in değişmediğini görelim.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# filtreleme

In [56]:
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
m.shape

(4, 3)

In [57]:
ikidenbüyük = m > 2

In [58]:
m[ikidenbüyük]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [59]:
m[m>5]

array([ 6,  7,  8,  9, 10, 11, 12])